language: node_js
node_js:
  - "stable"

script:
  - npm uninstall -g react-native-cli
  - npm i -g @react-native-community/cli
  - npm install
  - npm test
  - npm run build
  
deploy:
  provider: surge
  skip_cleanup: true
  domain: mfaisalpktravistesting.surge.sh
  project: ./build/

on: 
  branch: master
