language: node_js
node_js:
  - 'stable'

script:
  - npm install
  - npm test
  - npm run build
  - yarn precommit


deploy:
  provider: surge
  skip_cleanup: true
  domain: mfaisalpktravistesting.surge.sh
  project: ./build/

on: 
  branch: master
